#!/bin/bash
 
export _JAVA_AWT_WM_NONREPARENTING=1
xsetroot -cursor_name left_ptr

killall sxhkd
sxhkd &
 
# basic settings
bspc config border_width	2
bspc config normal_border_color "#282828"
bspc config focused_border_color "#ebdbb2" 
bspc config presel_border_color "#282828"
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config window_gap		15

# workspaces
bspc monitor DP-2 -d  爵      

# move windows with mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
 
bspc config split_ratio		0. 5
bspc config focus_follows_pointer false

# rules
# launch steam floating
bspc rule -a Steam state=floating

setxkbmap -layout us,ru -option grp:win_space_toggle
picom --experimental-backends --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
$HOME/.screenlayout/main.sh

$HOME/.config/polybar/launch.sh

