#!/bin/bash
 
export _JAVA_AWT_WM_NONREPARENTING=1
xsetroot -cursor_name left_ptr

killall sxhkd
sxhkd &
 
# basic settings
bspc config border_width 2
bspc config border_radius 0
bspc config normal_border_color "#232634"
# bspc config focused_border_color "#3EC669" 
bspc config focused_border_color "#ffffff"
# bspc config focused_border_color "#282828"
bspc config presel_border_color "#232634"
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config window_gap 0

# workspaces
bspc monitor DP-2 -d  爵      

# move windows with mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
 
bspc config split_ratio		0. 5
bspc config focus_follows_pointer false

# rules
# launch steam floating
# bspc rule -a Steam state=floating

setxkbmap -layout us,ru -option grp:win_space_toggle
picom --experimental-backends --config $HOME/.config/picom/picom.conf &

$HOME/.screenlayout/main.sh &
$HOME/.config/polybar/launch.sh &

feh /home/w1png/Pictures/wallpapers/o3757804.jpg --bg-fill &

killall -q redshift &
redshift -b 0.8:1 -l 55.7558:37.6173 -t 10000:5000 &

