#!/usr/bin/env sh

yabai -m config                                 \
    external_bar                 all:0:0        \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    split_ratio                  0.55           \
    split_type                   auto           \
    auto_balance                 off            \
    layout                       bsp            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   12             \
    window_shadow                off

yabai -m rule --add app="^V2BOX$"           manage=off
yabai -m rule --add app="^AmneziaVPN$"      manage=off
yabai -m rule --add app="^System Settings$" manage=off

echo "yabai configuration loaded.."
