export ZSH="$HOME/.oh-my-zsh"

eval "$(/opt/homebrew/bin/brew shellenv)"

zstyle ':omz:update' mode auto

ENABLE_CORRECTION="false"
HYPHEN_INSENSITIVE="true"

plugins=(
    git
    tmux
)

# PS1="%{$fg[yellow]%}%~ $%b "
export ZSH_THEME="awesomepanda"
export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_DEFAULT_SESSION_NAME="home"
export ZSH_TMUX_FIXTERM=true

unsetopt correct_all
source $ZSH/oh-my-zsh.sh

export EDITOR="nvim"

# misc
alias vim="nvim"
alias git_undo="git reset --soft HEAD~1"
alias ls="eza --icons"
alias ll="eza --icons -l"
alias tree="eza --icons --tree"
alias cat="bat"
alias cd="z"
alias sourcezsh="source ~/.zshrc"
alias k="kubectl --insecure-skip-tls-verify "

export GPG_TTY=$(tty)

eval "$(zoxide init zsh)"

export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

FZF_ALT_C_COMMAND="fd -t d . $HOME"
source <(fzf --zsh)

bindkey -r '^T'
bindkey '^G' fzf-file-widget

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
[ -s "/Users/w1png/.bun/_bun" ] && source "/Users/w1png/.bun/_bun"

# deno
export PATH="$HOME/.deno/bin:$PATH"

# go
export PATH=$PATH:$(go env GOPATH)/bin

# other PATH stuff
export PATH="$(brew --prefix)/opt/python@3.11/libexec/bin:$PATH"
export PATH="/Users/w1png/.local/bin:$PATH"
export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"
