export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="nicoulaj-custom"

plugins=(
  git
  python
  archlinux
  zsh-autosuggestions
  web-search
  copypath
  copyfile
  jsontools
)

source $ZSH/oh-my-zsh.sh

/usr/bin/setxkbmap -option "caps:swapescape"

# Aliases
# misc
alias vim="nvim"
alias py="python3.10"
alias git_undo="git reset --soft HEAD~1"
alias neofetch="neofetch --ascii_distro arch_small"
alias less="bat"
alias cat="bat"
alias tnode="node --loader ts-node/esm"

# dnf stuff
alias dnfin="sudo dnf install"
alias dnfs="dnf search"
alias dnfup="sudo dnf update && sudo dnf upgrade"
alias dnfrem="sudo dnf remove"

# Pacman
alias pacup="sudo pacman -Syu"
alias pacclean="sudo pacman -Sc && sudo pacman -Qtdq | sudo pacman -Rns -"


# Path
export CPATH=$CPATH:/usr/include/gtk-3.0
export CPATH=$CPATH:/usr/include/glib-2.0/
export CPATH=$CPATH:/lib64/glib-2.0/include/
export CPATH=$CPATH:/usr/include/pango-1.0/
export CPATH=$CPATH:/usr/lib64/gtk-3.0/3.0.0/
export CPATH=$CPATH:/usr/include/atk-1.0/
export CPATH=$CPATH:/usr/include/cairo/
